version: "3.7"
services:
  mailproxy:
    image: nginx:1.21.1
    container_name: nginx-mailfence-proxy
    restart: unless-stopped
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '465:465'
      - '993:993'


  l2tp:
    image: hwdsl2/ipsec-vpn-server
    container_name: l2tp-proxy
    restart: unless-stopped
    env_file: .env
    privileged: true
    volumes:
      - './.docker_data/ikev2-vpn-data:/etc/ipsec.d'
      - '/lib/modules:/lib/modules:ro'
    ports:
      - '500:500/udp'
      - '4500:4500/udp'


  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
     # - SERVERURL=wireguard.domain.com #optional
      - SERVERURL=${WIREGUARD_DOMAIN}
      - SERVERPORT=51820 #optional
      - PEERS=${WIREGUARD_PEERS} 
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.14.88.0 #optional
     # - ALLOWEDIPS=192.168.1.0/24,192.168.2.0/24 #optional
    volumes:
      - ./.docker_data/wireguard:/config
      - /lib/modules:/lib/modules
        # - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    restart: unless-stopped
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    volumes:
     - ./.docker_data/openvpn/conf:/etc/openvpn

